import React from 'react'
import {
  Play, Pause, Square, Circle, Mic, MicOff, Video, VideoOff, Monitor,
  Settings, HelpCircle, ChevronDown, ChevronRight, ChevronLeft, ChevronUp,
  X, Plus, Minus, Check, Download, Upload, Copy, Trash2, Edit2, Search,
  Scissors, ZoomIn, ZoomOut, RotateCcw, RotateCw, Volume2, VolumeX,
  Maximize2, Minimize2, SkipBack, SkipForward, Sliders, Camera,
  LayoutGrid, Film, BookOpen, User, Shield, Users, Link, Radio,
  Layers, Move, Crop, Type, ArrowLeft, ArrowRight, ArrowUp, ArrowDown,
  Sun, Moon, Clock, Star, MoreHorizontal, MoreVertical, Eye, EyeOff,
  RefreshCw, Save, Share2, Folder, FolderOpen, Music, Hash, Activity,
  AlertCircle, Info, CheckCircle, XCircle, Loader, PlayCircle, PauseCircle,
} from 'lucide-react'

const ICON_MAP = {
  play: Play, play_arrow: Play, play_circle: PlayCircle,
  pause: Pause, pause_circle: PauseCircle,
  stop: Square, stop_circle: Square,
  record: Circle, radio_button_checked: Radio,
  mic: Mic, mic_off: MicOff,
  videocam: Video, videocam_off: VideoOff, camera: Camera,
  monitor: Monitor, screen_share: Monitor,
  settings: Settings, tune: Settings,
  help: HelpCircle, help_circle: HelpCircle,
  chevron_down: ChevronDown, expand_more: ChevronDown,
  chevron_right: ChevronRight, chevron_left: ChevronLeft, chevron_up: ChevronUp,
  close: X, x: X,
  add: Plus, plus: Plus, remove: Minus,
  check: Check, done: Check,
  download: Download, file_download: Download,
  upload: Upload, cloud_upload: Upload,
  content_copy: Copy, copy: Copy,
  delete: Trash2, trash: Trash2,
  edit: Edit2, edit_2: Edit2,
  search: Search,
  content_cut: Scissors, scissors: Scissors, cut: Scissors,
  zoom_in: ZoomIn, zoom_out: ZoomOut,
  undo: RotateCcw, redo: RotateCw,
  volume_up: Volume2, volume_off: VolumeX, mute: VolumeX,
  fullscreen: Maximize2, fullscreen_exit: Minimize2,
  skip_previous: SkipBack, skip_next: SkipForward, fast_rewind: SkipBack, fast_forward: SkipForward,
  sliders: Sliders, tune_vert: Sliders,
  grid_view: LayoutGrid, grid: LayoutGrid,
  movie: Film, video_file: Film, film: Film,
  library_books: BookOpen, library: BookOpen,
  person: User, account_circle: User, user: User,
  security: Shield, lock: Shield,
  group: Users, people: Users,
  link: Link, link_2: Link,
  layers: Layers,
  open_with: Move, pan_tool: Move, move: Move,
  crop: Crop,
  title: Type, text_fields: Type, type: Type,
  arrow_back: ArrowLeft, arrow_forward: ArrowRight, arrow_upward: ArrowUp, arrow_downward: ArrowDown,
  light_mode: Sun, dark_mode: Moon,
  schedule: Clock, timer: Clock,
  star: Star, grade: Star,
  more_horiz: MoreHorizontal, more_vert: MoreVertical,
  visibility: Eye, visibility_off: EyeOff,
  refresh: RefreshCw,
  save: Save,
  share: Share2,
  folder: Folder, folder_open: FolderOpen,
  music_note: Music, audio: Music,
  tag: Hash,
  activity: Activity,
  warning: AlertCircle, error: AlertCircle,
  info: Info,
  check_circle: CheckCircle,
  cancel: XCircle,
  loading: Loader,
}

export default function Icon({ name = 'help', size = 20, className = '', style }) {
  const Component = ICON_MAP[name] || ICON_MAP[name?.toLowerCase()] || HelpCircle
  if (!ICON_MAP[name] && !ICON_MAP[name?.toLowerCase()]) {
    if (import.meta.env.DEV) console.warn(`[Icon] Unknown icon: "${name}", falling back to HelpCircle`)
  }
  return <Component size={size} className={className} style={style} strokeWidth={1.75} />
}
